Feature/#1 bootstrap react app
Recidiviz/case-triage pull request #12
Opened 2020-12-08 09:01 UTC by AlexK-ino

## Description of the change

> Description here

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes [#XXXX]

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-12-08 18:41 UTC, jessex requested changes
Congrats on the first PR in this new repo, @AlexK-ino! I left a variety of housekeeping comments for you.

Also, a couple of quick notes on our Github usage:
- Check out how I changed the _Related Issues_ portion of your PR description. The format I'm using there (with the square brackets removed) makes sure that the linked issue will be automatically closed when the PR is merged. Try to use that format going forward
- A very minor point, but try to avoid using `#` symbols in branch names because Github's overeager linking of issues/PRs will try to turn that into links in emails and will be a little bit annoying. This feature branch would have been fine with a name of `AlexK-ino/bootstrap-react-app`, for example

2020-12-08 18:41 UTC, jessex commented on .prettierrc.json
> +{
Can you make sure this prettierrc.json file looks identical to these two?
- https://github.com/Recidiviz/pulse-dashboard/blob/master/.prettierrc.json
- https://github.com/Recidiviz/justice-counts-components/blob/main/.prettierrc.json

2020-12-08 18:41 UTC, jessex commented on package.json
> +  "name": "case_triage",
We want these lines before `scripts` to read as the following:
```
{
  "name": "case-triage",
  "version": "0.1.0",
  "description": "A tool to improve outcomes for people under supervision",
  "private": true,
  "repository": "git@github.com:Recidiviz/case-triage.git",
  "author": "Recidiviz <team@recidiviz.org>",
  "license": "GNU General Public License v3",
  ...
```

2020-12-08 18:41 UTC, jessex commented on public/manifest.json
> +{
Can you make sure that this manifest.json file looks identical to this one:
- https://github.com/Recidiviz/pulse-dashboard/blob/master/public/manifest.json

And also can you include those same [.ico and .png assets from that repository](https://github.com/Recidiviz/pulse-dashboard/tree/master/public) over here?

2020-12-08 18:41 UTC, jessex commented on public/index.html
> +    <title>React App</title>
Let's change this to "Case Triage Tool"

2020-12-08 18:41 UTC, jessex commented on public/index.html
> +    <meta charset="utf-8" />
Let's make sure we include these highlighted lines from the index.html file in pulse-dashboard: 
- https://github.com/Recidiviz/pulse-dashboard/blob/master/public/index.html#L5-L12
- https://github.com/Recidiviz/pulse-dashboard/blob/master/public/index.html#L22-L26

2020-12-08 18:41 UTC, jessex commented on src/reportWebVitals.ts
> +import { ReportHandler, } from 'web-vitals';
Commenting here arbitrarily: can you make sure to include our standard license text on the top of all code files (that support comments)?
```
// Recidiviz - a data platform for criminal justice reform
// Copyright (C) 2020 Recidiviz, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// =============================================================================
```

2020-12-08 18:41 UTC, jessex commented on package.json
> +  "dependencies": {
Heads up: we use `yarn` at Recidiviz for installing dependencies and I don't see a `yarn.lock` file in the repo. Would you mind making sure the repo has the lock file and is set up to use yarn? Thanks!

2020-12-09 12:11 UTC, AlexK-ino commented on src/reportWebVitals.ts
> +import { ReportHandler, } from 'web-vitals';
@jessex Thanks for your comments, fixed everything

2020-12-09 12:12 UTC, AlexK-ino commented on package.json
> +  "dependencies": {
@jessex, thanks for your comments, fixed everything

2020-12-09 17:42 UTC, jessex approved these changes
Well done, @AlexK-ino. Thanks for getting this off the ground!

2020-12-09 17:43 UTC, merged