Alex k ino/create skeleton of the page
Recidiviz/case-triage pull request #18
Opened 2020-12-14 07:33 UTC by AlexK-ino

## Description of the change

> Description here

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes [#3 ]

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-12-14 17:42 UTC, jessex requested changes
Thanks, @AlexK-ino! From looking at the code, it looks like you've probably got the main components of the Triage view all stubbed out, but I can't do a full test and review because I can't start the app after checking out your branch.

When I run `yarn start`, I get this error in the console:
```
Failed to compile.

./src/App.tsx
Cannot find file: 'Header.tsx' does not match the corresponding name on disk: './src/components/header/Header'.
```

Do you see the same thing, @AlexK-ino?

2020-12-14 17:42 UTC, jessex commented on src/components/Header/ChangeState.tsx
> +      <Typography className={styles.stateName}>Idaho </Typography>
Why the space after Idaho? Intentional or unintentional?

2020-12-14 17:42 UTC, jessex commented on src/components/Header/ChangeState.tsx
> +// along with this program.  If not, see <https://www.gnu.org/licenses/>.
Nit: don't forget the line below at the end of the license text to help cleanly separate it from the source code:

```
// =============================================================================
```

Apply that here and in other license texts you've added without that line throughout this PR.

2020-12-14 17:42 UTC, jessex commented on src/components/Header/Notifications.tsx
> +  tittleNotifications: {
Typo: `titleNotifications`. But also it should probably be `notificationTitle` to read the most cleanly, right?

2020-12-14 17:42 UTC, jessex commented on src/components/mainContainer/MainContainer.tsx
> +export interface IMainContainerProps {}
I don't see where this is used. What is it for and what does the `I` mean here?

2020-12-14 17:42 UTC, jessex commented on src/components/mainContainer/MainContainer.tsx
> +export interface IMainContainerProps {}
I see you're doing this in other files, too, so it must just be a convention I don't know much about.

2020-12-14 17:42 UTC, jessex commented on src/components/mainContainer/components/Caseload/CardStatus.tsx
> +  tittleCard: {
We have the typo `tittle` instead of `title` in a variety of places in the PR. Let's clean those up.

2020-12-14 19:55 UTC, ohaibbq requested changes
Good progress here, and nice to meet you @AlexK-ino!

I'm sorry to add more requirements on at the PR-stage, but after chatting with the other front-end devs here, it seems like we'll want to change how the components & styles are structured in this PR. In order to maintain consistency across our repositories, we'd like to ask the following:

- Create the UI components without using any UI Framework (material-ui)
- Styles should be organized using [`styled-components`](https://styled-components.com/)

If your team is uncomfortable with using `styled-components`, perhaps we can adopt a Webpack style loader, and use [BEM](http://getbem.com/) with SCSS.

Let me know your thoughts.
Cheers~

2020-12-14 19:55 UTC, ohaibbq commented on src/components/Header/Notifications.tsx
> +  tittleNotifications: {
It seems that this typo happens across other files in the changeset, too.

2020-12-15 16:10 UTC, AlexK-ino commented
@ohaibbq, @jessex  Thanks for your comments, I will keep in mind from now on.
Corrected everything, changed the Material UI to styled components

2020-12-15 17:57 UTC, ohaibbq commented
Thanks for the update! I'm also unable to run this branch locally, facing the same error as @jessex.
`Cannot find file: 'Header.tsx' does not match the corresponding name on disk: './src/components/header/Header'.`

@AlexK-ino Is the `yarn run start` script the correct method to run the app?

Lastly, one thing to take note of, I'd like for us to start extracting common style variables into a separate javascript module, then interpolating them into our styled components. For example, something like this:
```js
// src/styles.js
const styles = { MAIN_FONT: 'Libre Franklin' };
export default styles;

// src/components/mainContainer/components/Caseload/CardState.tsx 
import styles from '/src/styles.js
const TitleCaseload = styled.p`
  font-family: {styles.MAIN_FONT};
  font-weight: 400;
  margin-bottom: 24px;
  margin-top: 48px;
  font-size: 16px;
`;
```

2020-12-15 18:41 UTC, ohaibbq commented on src/components/mainContainer/components/Caseload/CardState.tsx
> +  max-width: 408;
Can we specify the units here?

2020-12-16 08:07 UTC, AlexK-ino commented on src/components/mainContainer/components/Caseload/CardState.tsx
> +  max-width: 408;
I apologize, was in a hurry, did not pay attention.

2020-12-16 08:08 UTC, AlexK-ino commented
@ohaibbq @jessex 
Hope I was able to solve the project compilation issue

2020-12-17 02:33 UTC, ohaibbq approved these changes
This is looking good, @AlexK-ino! There are some small style differences from the mock, but lets sort those out as we flesh out the components.

As we continue developing, we'll need to make sure we replace the static content in our mock components with the appropriate props for reusability.

2020-12-17 04:08 UTC, jessex approved these changes

2020-12-17 04:09 UTC, merged