Alex k ino/triage list client list
Recidiviz/case-triage pull request #19
Opened 2020-12-22 07:08 UTC by AlexK-ino

## Description of the change
Added:

- customized progress bar
- tooltip box
- customized checkbox
- button "Snooze"
- mock data with American format date

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #7 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-12-22 14:57 UTC, Wmaileq requested changes
Initial review

2020-12-22 14:57 UTC, Wmaileq commented on .eslintignore
> +reportWebVitals.ts
Add the new line

2020-12-22 14:57 UTC, Wmaileq commented on public/index.html
> +  <body style="margin: 0;">
Use global styles in favor of inline styles

2020-12-22 14:57 UTC, Wmaileq commented on src/components/Checkbox.tsx
> +  display: ${(props: Props) => (props.checked ? "flex" : "none")};
Use `props destructuring`.

2020-12-22 14:57 UTC, Wmaileq commented on src/components/ClientCard.tsx
> +  const setProgressColor = () => {
`getProgressColor`
Also, as an alternative, you could do it as `IIFE` or `useMemo` and name it just `progressColor`.

2020-12-22 14:57 UTC, Wmaileq commented on src/components/IndividualCards.tsx
> +  const handleChangeUser = (val: User) => {
Maybe just `changeUser` or `setUser`, or `setUserData`?

2020-12-22 14:57 UTC, Wmaileq commented on src/components/ClientCard.tsx
> +`;
Please, add new lines between function declarations and before return operator. It looks too dense now.

Also, maybe separate styles into a different file and name it `*.styles.tsx`, thoughts?

2020-12-22 14:57 UTC, Wmaileq commented on src/App.test.tsx
> +import { App } from "./App";
Prefer `default export`

2020-12-22 14:57 UTC, Wmaileq commented on src/components/ClientCard.tsx
> +  expanded: boolean;
Boolean constants should start with `is`, `isExanded`, `isChecked`

2020-12-22 14:57 UTC, Wmaileq commented on src/components/ClientCard.tsx
> +  const handleChangeChecked = (
What is the mission of `handle` keyword here? Maybe name these functions `toggleIsChecked`, `toggleIsExpanded`, ...?

2020-12-22 21:12 UTC, jessex requested changes
I tried to start the app locally via `yarn start` to test this and it failed to compile (see screenshot below). Is that happening for you, @AlexK-ino? I know we had a similar issue on an earlier PR where @ohaibbq and I could not start it locally, so if you're not trying to run this locally via `yarn start`, you definitely should do so before issuing PRs.

2020-12-23 02:09 UTC, ohaibbq commented on .github/pull_request_template.md
> +These boxes should be isChecked by reviewers prior to merging:
I don't think you meant to find/replace this.

2020-12-23 20:10 UTC, ohaibbq commented
Thanks, Alex! Its looking good. Some styling issues to fix up before I review the code.

Please reference the checklist with my attached annotated image.

- [ ] 1. The font color and the circle fill color is based on what % full the circle is. Please see the mocks for the appropriate colors for the various circle states. (0,1,2,3,4,5,6,7). The circle height should be as tall as the 2 lines of text to the right
- [ ] 2. There is too much whitespace between the circle and the first column.
- [ ] 3. There is too much whitespace between the two lines of text
- [ ] 4. The "tooltip" text does vertical alignment does not match the alignment specified in the mocks
- [ ] 5. The left side of the exclamation icon should align with the left side of the circle 
- [ ] 6. On smaller screen sizes, an odd left border appears on the list item
- [ ] 7. When hovering an ID link, the text falls out of left alignment with the line above
- [ ] 8. The tooltip is not activated via click. It should be shown by default and is persistent
- [ ] 9. The tooltip is missing the arrow icon on the right side
- [ ] 10. The bottom border list items needs to be consistent. There is currently an inconsistency based on whether or not item has a tooltip
- [ ] 11. Please allow for some dates to have an red indicator icon to the right hand side. This will signify that the date is past due
![Client List](https://user-images.githubusercontent.com/437360/103033688-e09ecd00-4517-11eb-9852-62e2b7c25539.png)

2020-12-24 14:30 UTC, AlexK-ino commented
Hello @ohaibbq, @jessex!
Thanks for the comment, I corrected all the above, I'm not sure what, I understood point # 10 correctly, but I corrected the shadows.

Regarding the point, I initially did not understand its purpose and therefore flew out of my head, I apologize.

The problem with the build was due to an accidental prettier rule change. I also apologize for this incident. I will try not to make similar mistakes in the future.

2020-12-26 19:14 UTC, ohaibbq approved these changes
@AlexK-ino This looks so good, nice work!

Let's get this merged. Could you review #24 and start work on #23  and #25?

2021-01-05 00:05 UTC, jessex approved these changes
Looks great, @AlexK-ino! Looks like there are some merge conflicts but don't block on me.

2021-01-05 00:11 UTC, ohaibbq commented
@AlexK-ino could you fix the merge conflicts and get this PR merged?

2021-01-11 08:35 UTC, AlexK-ino commented
@ohaibbq, I fixed the conflicts, but unfortunately, I cannot merge branches, there is no access

2021-01-11 19:27 UTC, merged