feat: 🎸 Added MVP-Version of caseload health-card
Recidiviz/case-triage pull request #26
Opened 2020-12-28 03:22 UTC by MeloncholyShiro

## Description of the change
!PR only for rewiew and feedback. In my opinion, it's not ready for a merger yet

This is MVP Version on health card (issue #5 ).

If possible, leave feedback, what is needed in terms of functionality, what is and what is not so, for much to implement was taken from the head. Thank you in advance!

Generation "Percentage" is random, to see what different versions of cards look like - just refresh the page.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Work in progress #5 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-12-28 09:22 UTC, Wmaileq requested changes
Please move props destructuring into components declarations.

2020-12-28 09:22 UTC, Wmaileq commented on src/components/KebabMenu.tsx
> +const Kebab = styled.div`
Maybe this is `button`?

2020-12-28 09:22 UTC, Wmaileq commented on src/components/KebabMenu.tsx
> +  const { onClick } = props;
Move one line higher

2020-12-28 09:22 UTC, Wmaileq commented on src/components/Select.tsx
> +  items: T[];
Usually, items consist of `value` and `label`(vale and label could be different very often), so if your component pretends to be universal and should be used in other places of the app, you should use common patterns.

But it's up to you.

2020-12-28 09:22 UTC, Wmaileq commented on src/components/Select.tsx
> +  const toggling = () => setIsOpen(!isOpen);
Functions usually named by verbs and not nouns

2020-12-28 09:22 UTC, Wmaileq commented on src/styles/SelectItem.styles.tsx
> +  /* I don't know :( */
Ask for mocks in the issue or PRD.

2020-12-29 17:51 UTC, ohaibbq requested changes
This is looking good! +1 to the feedback from @Wmaileq.

2020-12-29 17:51 UTC, ohaibbq commented on src/components/Caseload.tsx
> +      <CaseloadHealthCard officerPercentile={generatePercentile()} />
Could we implement functionality so that the card will update it's percentile when the filters (1w, 1m, 3m), are updated?

2020-12-29 17:51 UTC, ohaibbq commented on src/components/CaseloadHealthCard.tsx
> +  okey: {
`okey` -> `okay`

2020-12-29 17:51 UTC, ohaibbq commented on src/components/CaseloadHealthCard.tsx
> +      )}
Can we refactor the styles fo that we don't need to the duplicate templates for `chart.position === "below"` and `chart.position === "above"`?

2021-01-14 22:48 UTC, ohaibbq approved these changes

2021-01-14 22:48 UTC, merged