Alex k ino/progress pie component
Recidiviz/case-triage pull request #27
Opened 2020-12-29 12:24 UTC by AlexK-ino

## Description of the change

ProgressBar has been moved to a separate component and added to the storybook

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #23

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-12-29 18:22 UTC, ohaibbq requested changes

2020-12-29 18:22 UTC, ohaibbq commented on src/styles/ProgressPie.styles.tsx
> +import ProgressBar from "react-customizable-progressbar";
This module was not added to our `package.json`

2020-12-30 09:47 UTC, AlexK-ino commented on src/styles/ProgressPie.styles.tsx
> +import ProgressBar from "react-customizable-progressbar";
Hello, Dan!

Perhaps I didn't quite get the point. To clarify:
My package.json has this module. Or is it not meant to use third-party modules?
![Снимок экрана 2020-12-30 в 12 46 59](https://user-images.githubusercontent.com/75606430/103343441-1fdf9780-4a9d-11eb-91ca-1a56f74de6ec.png)

2020-12-30 10:59 UTC, AlexK-ino commented on .eslintrc.js
> +    "react/jsx-one-expression-per-line": "off",
![Снимок экрана 2020-12-30 в 13 56 56](https://user-images.githubusercontent.com/75606430/103347049-e3189e00-4aa6-11eb-8427-35380ca8e4b8.png)

These rules do not violate the `airbnb` style, with the exception of `"object-curly-newline",` which conflicts with prettier

2021-01-12 11:53 UTC, AlexK-ino commented on src/styles/ProgressPie.styles.tsx
> +import ProgressBar from "react-customizable-progressbar";
Dan, сould you give an explanation? Maybe I misunderstood?

2021-01-12 23:03 UTC, ohaibbq commented on src/styles/ProgressPie.styles.tsx
> +import ProgressBar from "react-customizable-progressbar";
I must have had an issue with my local environment. It works fine now!

2021-01-12 23:03 UTC, ohaibbq approved these changes

2021-01-12 23:04 UTC, merged