Alex k ino/client card to story book
Recidiviz/case-triage pull request #29
Opened 2020-12-30 11:37 UTC by AlexK-ino

## Description of the change

Added clientCard to StoryBook
Added dropMenu to execute progress bar

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #25

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [X] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-01-13 01:53 UTC, ohaibbq requested changes
This is looking great, Alex!

A few changes I'd like to see:
- [x] Include whitespace between first name, surname
- [ ] Include whitespace between first name, surname
- [ ] Extract the `ProgressMenu` into a generic `Tooltip` component
  - [ ] Can be triggered by Hover or Click
  - [ ] Contents are specified by a children prop
  - [ ] Add to Storybook
- [ ]  Remove `ProgressMenuItem.onClick` / `handlerProgressMenu`
  *  This functionality is good for demos, but not something we'd like in the app

2021-01-13 01:53 UTC, ohaibbq commented on src/stories/ClientCard.stories.tsx
> +  tooltip: "Something Tooltip! #1",
The tooltip should be moved to `ClientCard` props, rather than being stored in the User.

2021-01-13 01:53 UTC, ohaibbq commented on src/stories/ClientCard.stories.tsx
> +  isChecked: false,
Please move `isChecked` into the `ClientCard` props

2021-01-13 01:53 UTC, ohaibbq commented on src/stories/ClientCard.stories.tsx
> +  isSnoozed: false,
Please move `isSnoozed` into the `ClientCard` props

2021-01-13 11:15 UTC, AlexK-ino commented on src/stories/ClientCard.stories.tsx
> +  tooltip: "Something Tooltip! #1",
Dan, thanks for the amendments, I would like to clarify, I understand correctly that the tooltip will be individual for each user and there is also a chance that it will not be there?

2021-01-13 19:22 UTC, ohaibbq commented on src/stories/ClientCard.stories.tsx
> +  tooltip: "Something Tooltip! #1",
That's correct! The tooltip existence may dependent on factors outside the User, so we want finer grain control over when it is displayed.

I could also imagine a case in which we are rendering 2 cards for a single user, each with a unique tooltip.

2021-01-14 19:47 UTC, ohaibbq approved these changes

2021-01-14 19:49 UTC, merged

2021-01-14 19:50 UTC, ohaibbq commented
Thanks Alex! Could you start on https://github.com/Recidiviz/case-triage/issues/31 next?