Add Typography & Color Palettes
Recidiviz/case-triage pull request #55
Opened 2021-02-03 00:03 UTC by ohaibbq

## Description of the change

This is a first attempt at adding typography and color palettes to our component library.

### Palette Storybook
<img width="1792" alt="Screen Shot 2021-02-02 at 3 59 44 PM" src="https://user-images.githubusercontent.com/437360/106678636-f91af200-656f-11eb-8e93-aebcb5cc0981.png">

### Typography Storybook
<img width="1788" alt="Screen Shot 2021-02-02 at 3 59 51 PM" src="https://user-images.githubusercontent.com/437360/106678641-fc15e280-656f-11eb-8fd9-37514cc05ef4.png">

### Case Triage usage
<img width="1792" alt="Screen Shot 2021-02-02 at 4 00 32 PM" src="https://user-images.githubusercontent.com/437360/106678644-fcae7900-656f-11eb-8c2f-8b8c8e1c0695.png">

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Checklists

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-03 19:43 UTC, macfarlandian reviewed
this is super cool overall but i have a few nitpicky comments

2021-02-03 19:43 UTC, macfarlandian commented on src/components/Typography/Headings.tsx
> +  font-size: 70px;
here is a fun thing I have been doing in Spotlight v2: sizing [just about everything in rem](https://zellwk.com/blog/rem-vs-em/) instead of px using a [utility function from polished](https://polished.js.org/docs/#rem). it doesn't always work well in animation but otherwise seems OK? (I am not 100% sure, honestly, if this is Actually Good but it's an idea I wanted to put out there)

2021-02-03 23:39 UTC, ohaibbq commented on src/styles/Theme.ts
> +
These don't have names at the moment, but it'd be neat if they did :)

2021-02-03 23:58 UTC, ohaibbq commented on src/components/Typography/Headings.tsx
> +  children: ReactChild | ReactChild[];
It seems like they're not!

2021-02-04 00:56 UTC, macfarlandian requested changes

2021-02-04 00:56 UTC, macfarlandian commented on src/styles/index.ts
> +  polishedRem(size, fonts.sizes.base);
FWIW if size is a number it's treated as a pixel value, which is either a nice shortcut or not explicit enough, depending on your perspective

2021-02-04 00:56 UTC, macfarlandian commented on src/styles/GlobalStyle.ts
> +  }
I gather, from my admittedly limited reading on the subject, that setting a base font size like this is [frowned upon](https://www.24a11y.com/2019/pixels-vs-relative-units-in-css-why-its-still-a-big-deal/) for accessibility reasons, and letting this come from the browser settings (both here and in your custom `rem` function) would increase responsiveness

2021-02-04 18:00 UTC, macfarlandian approved these changes
🥇

2021-02-04 19:18 UTC, merged